### ISSUE TITLE
Blocklet configuration issues on openstack infrastructure

### ISSUE THREAD

**Issue by robroyhobbs** [ArcBlock/blocklets#31]
<img width="1867" alt="Screen Shot 2020-06-01 at 3 13 54 PM" src="https://user-images.githubusercontent.com/41485426/83461502-c6878b00-a41d-11ea-9cff-76a7f0f0979f.png">
<img width="1654" alt="Screen Shot 2020-06-01 at 2 40 05 PM" src="https://user-images.githubusercontent.com/41485426/83461505-c7b8b800-a41d-11ea-96a8-64d194153e39.png">
<img width="1265" alt="Screen Shot 2020-06-01 at 2 39 20 PM" src="https://user-images.githubusercontent.com/41485426/83461508-c9827b80-a41d-11ea-90f3-eee4d039a072.png">

Forwarding issues from OpenStack admin specifically around deploying blocklets on OpenStack vms. I will get an IP address of a VM that we can test on our own. 

I’m getting issues with running this on Openstack.  In an Openstack instance, there is no public IP set in the OS’s interface config, just an internal IP, and neutron does routing for external IPs, bridging to the internal (I think AWS works like this too?). So if the domain in the /home/ubuntu/.abtnode.yml file is set to the external IP, blocklets seem to fail to start since it tries to use the external IP (which isn’t listed in the instance interface config). If it’s set to the internal, blocklets install correctly and can start, but the config pages can fail to load.
\
I’ve tested out the blockchain, and the static demo blocklets.

Static Demo:

Internal IP:

Setting up with the openstack internal IP, the blocklet installs, but the public interface link shows the internal IP. So clicking the link fails, but going to the public IP with the static demo port works and loads up the game.

 

External IP:

Setting it up with an external IP and the blocklet fails to start, with the following error on the node:

{ Error: listen EADDRNOTAVAIL: address not available 23.111.76.96:8091

    at Server.setupListenHandle [as _listen2] (net.js:1263:19)

    at listenInCluster (net.js:1328:12)

    at doListen (net.js:1461:7)

    at process._tickCallback (internal/process/next_tick.js:63:19)

    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)

    at startup (internal/bootstrap/node.js:283:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

  code: 'EADDRNOTAVAIL',

  errno: 'EADDRNOTAVAIL',

  syscall: 'listen',

  address: '23.111.76.96',

  port: 8091 }

 

 

Blockchain:

Internal IP:

It will setup, but the management page wont load though the node’s management GUI.  If you go directly to the public IP and the port, it loads but doesn’t allow you to create a chain. The following error appears: Request failed with status code 403
 
External IP:

It will setup, but once you try to setup a chain it will error after downloading the chain version. Attached is a screenshot. I don’t see any errors on the node apart from:

ubuntu@testblockchain:~/.abtnode/logs/blockchain-manager$ tail error.log

Setting authPrincipal in claims object is not recommended, and may break things

Setting authPrincipal in claims object is not recommended, and may break things

**Comment by robroyhobbs** [comment]
note, no issues deploying the node and getting it configured.

**Comment by robroyhobbs** [comment]
<img width="1231" alt="Screen Shot 2020-06-01 at 3 27 32 PM" src="https://user-images.githubusercontent.com/41485426/83461773-66ddaf80-a41e-11ea-9bca-5a9a4e9e7288.png">

**Comment by mave99a** [comment]
Looks like the Port is not available for binding

**Comment by polunzh** [comment]
It seems to be a problem with IP and port, similar to the problem with docker.
